href:
  rails_tutorial: "https://www.railstutorial.org/"
  book_page: "https://www.railstutorial.org/book"
  author_page: "https://www.michaelhartl.com/"
  news_page: "https://news.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
  rails_help_page: "https://www.railstutorial.org/help"
  learn_enough_page: "https://www.learnenough.com/"
  screencast_page: "https://screencasts.railstutorial.org/"
  rails_contact_page: "https://www.railstutorial.org/contact"

validation:
  name_max_digits: 50
  email_max_digits: 255
  password_min_digits: 6

regex:
  email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'

gravatar:
  href: "https://secure.gravatar.com/avatar"

pagy:
  limit_per_page: 30

pw_res:
  expire: 2
