href:
  rails_tutorial: "https://www.railstutorial.org/"
  book_page: "https://www.railstutorial.org/book"
  author_page: "https://www.michaelhartl.com/"
  news_page: "https://news.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
  rails_help_page: "https://www.railstutorial.org/help"
  learn_enough_page: "https://www.learnenough.com/"
  screencast_page: "https://screencasts.railstutorial.org/"
  rails_contact_page: "https://www.railstutorial.org/contact"
